site_name: saucey
pages:
- [index.md, Home]
- ['./Get_Started.md', 'saucey']
- ['./Available_Step_Definitions.md', 'saucey']
- ['./Reporting_and_More.md', 'saucey']
- ['./Caveats_and_Issues.md', 'saucey']
- ['./Release_Notes.md', 'saucey']
- ['testing/QA_Explained.md', 'general']
- ['testing/Testing_Tutorial_And_Guidelines.md', 'general']
- ['testing/Click_Through_Verification.md', 'general']
- ['testing/Regression_Test_Plan.md', 'test plans']
- ['testing/Prism_Ad_Test_Plan.md', 'test plans']
theme: readthedocs
repo_url: https://github.com/getsaucey/docs.saucey.io